[project]
name = "Industrial-relations-club"
version = "0.1.0"
description = "A little website to help WA's doctors understand their pay packet."
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["matplotlib>=3.10.7", "pandas>=2.3.3"]
